### ISSUE TITLE
[Feature Request] Enable Copr RPM build for Fedora 39 and 40

### ISSUE THREAD

**Issue by runlevel5** [nazunalika/rpmspecs-crispy-doom#1]
as titled. Many thanks in advance.

cc @nazunalika

**Comment by nazunalika** [comment]
Catching up on my tickets. I know this was almost a year ago, but Fedora 39, 40, rawhide, and mageia 9 is now available.

**Comment by runlevel5** [comment]
@nazunalika many thanks
